workflows:
  flutter-build-ios:
    environment:
      groups:
        - my_project_secrets
      flutter: stable
      xcode: latest
      java: 17
    integrations:
      app_store_connect: "Codemagic_MH"
    signing:
      xcode_project: "ios/Runner.xcodeproj"
      # Cámbialo a false para forzar el uso de tu perfil específico
      automatic_signing: false 
      provisioning_profile_type: app_store
      # Aquí es donde vinculas el nombre que pusiste en la web
      provisioning_profiles:
        - MapHunter_AppStore
      entitlements: ios/Runner/Runner.entitlements
    scripts:


      - name: Clean Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Clean and install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock ~/Library/Caches/CocoaPods
          pod repo update
          pod install
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign