workflows:
  flutter-build-ios:
    environment:
      groups:
        - my_project_secrets
      flutter: stable
      xcode: latest
      java: 17
    signing:
      xcode_project: "ios/Runner.xcodeproj"
      automatic_signing: true
      provisioning_profile_type: app_store
      entitlements: ios/Runner/Runner.entitlements
    scripts:
      - name: Create .env file
        script: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "PAGO_PAGO_API_URL=$PAGO_PAGO_API_URL" >> .env
          echo "PAGO_PAGO_CANCEL_URL=$PAGO_PAGO_CANCEL_URL" >> .env
          echo "PAGO_PAGO_WITHDRAW_URL=$PAGO_PAGO_WITHDRAW_URL" >> .env
          echo "PAGO_PAGO_WEBHOOK_URL=$PAGO_PAGO_WEBHOOK_URL" >> .env
          echo "PAGO_PAGO_API_KEY=$PAGO_PAGO_API_KEY" >> .env
          echo "Created .env file with content:"
          cat .env


      - name: Clean Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Clean and install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock ~/Library/Caches/CocoaPods
          pod repo update
          pod install
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign