import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import '../../models/clue.dart';
import '../../../auth/providers/player_provider.dart';
import '../../providers/game_provider.dart';
import '../../../../core/theme/app_theme.dart';
import 'game_over_overlay.dart';
import '../../../mall/screens/mall_screen.dart';
import '../../../../shared/widgets/animated_cyber_background.dart';
import '../race_track_widget.dart';
import '../../utils/minigame_logic_helper.dart';

class DrinkMixerMinigame extends StatefulWidget {
  final Clue clue;
  final VoidCallback onSuccess;

  const DrinkMixerMinigame({
    super.key,
    required this.clue,
    required this.onSuccess,
  });

  @override
  State<DrinkMixerMinigame> createState() => _DrinkMixerMinigameState();
}

class _DrinkMixerMinigameState extends State<DrinkMixerMinigame> {
  // Base Colors
  static const Color _cRed = Colors.redAccent;
  static const Color _cBlue = Colors.blueAccent;
  static const Color _cYellow = Colors.yellowAccent;

  // Game Logic
  late Color _targetColor;
  double _redAmount = 0;
  double _blueAmount = 0;
  double _yellowAmount = 0;
  int _cocktailsServed = 0;
  static const int _targetCocktails = 5;
  
  // Possible target colors generated by EXACTLY the same logic as the mixing
  List<Color> get _possibleTargets => [
    _mix(1, 0, 0), // Magma Puro
    _mix(0, 1, 0), // Cyber Puro
    _mix(0, 0, 1), // Solar Puro
    _mix(1, 1, 0), // Morado (R+B)
    _mix(1, 0, 1), // Naranja (R+Y)
    _mix(0, 1, 1), // Verde (B+Y)
  ];

  Color _mix(double r, double b, double y) {
    double total = r + b + y;
    if (total <= 0) return Colors.white10;
    
    double rP = r / total;
    double bP = b / total;
    double yP = y / total;

    int red = ((_cRed.red * rP) + (_cBlue.red * bP) + (_cYellow.red * yP)).toInt();
    int green = ((_cRed.green * rP) + (_cBlue.green * bP) + (_cYellow.green * yP)).toInt();
    int blue = ((_cRed.blue * rP) + (_cBlue.blue * bP) + (_cYellow.blue * yP)).toInt();

    return Color.fromARGB(255, red, green, blue);
  }

  // Timer State
  late Timer _timer;
  int _secondsRemaining = 90;
  bool _isGameOver = false;
  
  // UI State
  bool _showOverlay = false;
  String _overlayTitle = "";
  String _overlayMessage = "";
  bool _canRetry = false;
  bool _isVictory = false;
  bool _showShopButton = false;

  @override
  void initState() {
    super.initState();
    _generateTarget();
    _startTimer();
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  void _generateTarget() {
    setState(() {
      final targets = _possibleTargets;
      _targetColor = targets[Random().nextInt(targets.length)];
      _redAmount = 0;
      _blueAmount = 0;
      _yellowAmount = 0;
    });
  }

  void _startTimer() {
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (!mounted) return;
      final gameProvider = Provider.of<GameProvider>(context, listen: false);
      if (gameProvider.isFrozen) return;

      if (_secondsRemaining > 0) {
        setState(() => _secondsRemaining--);
      } else {
        _handleTimeOut();
      }
    });
  }

  void _handleTimeOut() {
    _timer.cancel();
    _loseLife("┬íTiempo agotado!");
  }

  void _addRed() {
    if (_isGameOver || (_redAmount + _blueAmount + _yellowAmount) >= 1.0) return;
    HapticFeedback.lightImpact();
    setState(() {
      _redAmount = (_redAmount + 0.5).clamp(0.0, 1.0);
    });
  }

  void _addBlue() {
    if (_isGameOver || (_redAmount + _blueAmount + _yellowAmount) >= 1.0) return;
    HapticFeedback.lightImpact();
    setState(() {
      _blueAmount = (_blueAmount + 0.5).clamp(0.0, 1.0);
    });
  }

  void _addYellow() {
    if (_isGameOver || (_redAmount + _blueAmount + _yellowAmount) >= 1.0) return;
    HapticFeedback.lightImpact();
    setState(() {
      _yellowAmount = (_yellowAmount + 0.5).clamp(0.0, 1.0);
    });
  }

  void _resetMix() {
    HapticFeedback.mediumImpact();
    setState(() {
      _redAmount = 0;
      _blueAmount = 0;
      _yellowAmount = 0;
    });
  }

  Color _getCurrentColor() {
    return _mix(_redAmount, _blueAmount, _yellowAmount);
  }

  void _checkMix() {
    if (_isGameOver) return;
    Color current = _getCurrentColor();
    if (current.value == _targetColor.value) { 
      _handleWin();
    } else {
      HapticFeedback.heavyImpact();
      _loseLife("Mezcla incorrecta.");
    }
  }

  void _handleWin() {
    setState(() {
      _cocktailsServed++;
    });

    if (_cocktailsServed >= _targetCocktails) {
      _timer.cancel();
      setState(() {
        _isGameOver = true;
        _isVictory = true;
      });
      HapticFeedback.heavyImpact();
      _showOverlayState(
        title: "¡MAESTRO COCTELERO!",
        message: "Has servido los $_targetCocktails cócteles con éxito.",
        victory: true,
      );
    } else {
      HapticFeedback.mediumImpact();
      _generateTarget();
    }
  }

  void _loseLife(String reason) async {
    _timer.cancel();
    int livesLeftCount = await MinigameLogicHelper.executeLoseLife(context);
    bool livesLeft = livesLeftCount > 0;
    
    if (mounted) {
      if (!livesLeft) {
        setState(() => _isGameOver = true);
        _showOverlayState(
          title: "SISTEMA BLOQUEADO",
          message: "$reason - Sin vidas.",
          showShop: true,
        );
      } else {
        _showOverlayState(
          title: "ERROR DE COLOR",
          message: "$reason -1 Vida.",
          retry: true,
        );
      }
    }
  }

  void _showOverlayState({required String title, required String message, bool retry = false, bool victory = false, bool showShop = false}) {
    setState(() {
      _showOverlay = true;
      _overlayTitle = title;
      _overlayMessage = message;
      _canRetry = retry;
      _isVictory = victory;
      _showShopButton = showShop;
    });
  }

  void _handleGiveUp() {
    _timer.cancel();
    _loseLife("Abandono.");
  }

  @override
  Widget build(BuildContext context) {
    final currentColor = _getCurrentColor();

    return Stack(
      children: [
        // Content Area 
        SingleChildScrollView(
          physics: const ClampingScrollPhysics(),
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Column(
              children: [
                const SizedBox(height: 5),

                // BARRA DE ESTADO (Vidas, Progreso y Tiempo)
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                  child: Row(
                    children: [
                      _buildStatPill(Icons.favorite, "x${Provider.of<GameProvider>(context).lives}", AppTheme.dangerRed),
                      const SizedBox(width: 8),
                      _buildStatPill(Icons.local_bar, "$_cocktailsServed/$_targetCocktails", AppTheme.accentGold),
                      const Spacer(),
                      _buildStatPill(Icons.timer_outlined, "${(_secondsRemaining ~/ 60)}:${(_secondsRemaining % 60).toString().padLeft(2, '0')}", _secondsRemaining < 10 ? AppTheme.dangerRed : Colors.white70),
                    ],
                  ),
                ),

                const SizedBox(height: 15),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    // VERTICAL CONTROLS
                    Container(
                      padding: const EdgeInsets.symmetric(vertical: 15, horizontal: 8),
                      decoration: BoxDecoration(
                        color: Colors.white.withOpacity(0.04),
                        borderRadius: BorderRadius.circular(15),
                        border: Border.all(color: Colors.white10),
                      ),
                      child: Column(
                        children: [
                          _buildVertButton("RED", _cRed, _addRed),
                          const SizedBox(height: 12),
                          _buildVertButton("BLUE", _cBlue, _addBlue),
                          const SizedBox(height: 12),
                          _buildVertButton("YEL", _cYellow, _addYellow),
                          const SizedBox(height: 15),
                          IconButton(
                            onPressed: _resetMix,
                            icon: const Icon(Icons.refresh, color: Colors.white38, size: 20),
                          ),
                        ],
                      ),
                    ),
                    
                    // THE MIXER INTERFACE
                    Expanded(
                      child: Column(
                        children: [
                          const Text(
                            "IGUALA EL CÓCTEL",
                            style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w900, letterSpacing: 1.5, decoration: TextDecoration.none),
                          ),
                          const Text(
                            "Mezcla los ingredientes para igualar el color objetivo.",
                            style: TextStyle(color: Colors.white38, fontSize: 9, fontStyle: FontStyle.italic, decoration: TextDecoration.none),
                          ),
                          const SizedBox(height: 15),
                          // COMPARISON
                          Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              _buildColorCircle("OBJETIVO", _targetColor),
                              const Padding(
                                padding: EdgeInsets.symmetric(horizontal: 10),
                                child: Icon(Icons.compare_arrows, color: Colors.white12, size: 16),
                              ),
                              _buildColorCircle("TU MEZCLA", currentColor),
                            ],
                          ),
                          const SizedBox(height: 15),
                          // COMPACT GLASS
                          Container(
                            width: 80,
                            height: 100,
                            decoration: BoxDecoration(
                              color: Colors.white.withOpacity(0.05),
                              borderRadius: const BorderRadius.only(
                                bottomLeft: Radius.circular(30),
                                bottomRight: Radius.circular(30),
                                topLeft: Radius.circular(5),
                                topRight: Radius.circular(5),
                              ),
                              border: Border.all(color: Colors.white12, width: 2),
                            ),
                            child: Stack(
                              alignment: Alignment.bottomCenter,
                              children: [
                                AnimatedContainer(
                                  duration: const Duration(milliseconds: 250),
                                  width: double.infinity,
                                  height: 100 * ((_redAmount + _blueAmount + _yellowAmount) / 1.0).clamp(0.0, 1.0),
                                  decoration: BoxDecoration(
                                    color: currentColor,
                                    borderRadius: const BorderRadius.only(
                                      bottomLeft: Radius.circular(28),
                                      bottomRight: Radius.circular(28),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: 15),
                          // SERVE BUTTON
                          SizedBox(
                            width: 140,
                            child: ElevatedButton(
                              onPressed: _checkMix,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: AppTheme.accentGold,
                                foregroundColor: Colors.black,
                                padding: const EdgeInsets.symmetric(vertical: 14),
                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                              ),
                              child: const Text("SERVIR CÓCTEL", style: TextStyle(fontSize: 14, fontWeight: FontWeight.w900)),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 30),
                
                // BOTÓN DE RENDICIÓN ABAJO
                Padding(
                  padding: EdgeInsets.zero,
                  child: OutlinedButton(
                    onPressed: _handleGiveUp,
                    style: OutlinedButton.styleFrom(
                      minimumSize: const Size(double.infinity, 45),
                      side: BorderSide(color: AppTheme.dangerRed.withOpacity(0.6), width: 1),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                    child: Text(
                      "RENDIRSE",
                      style: TextStyle(color: AppTheme.dangerRed.withOpacity(0.8), fontSize: 11, fontWeight: FontWeight.bold),
                    ),
                  ),
                ),
                const SizedBox(height: 30),
              ],
            ),
          ),
        ),

        if (_showOverlay)
          GameOverOverlay(
            title: _overlayTitle,
            message: _overlayMessage,
            isVictory: _isVictory,
            onRetry: _canRetry ? () {
              setState(() {
                _showOverlay = false;
                _isGameOver = false;
                _isVictory = false;
                _cocktailsServed = 0;
                _secondsRemaining = 90;
                _generateTarget();
                _startTimer();
              });
            } : null,
            onGoToShop: _showShopButton ? () async {
              await Navigator.push(context, MaterialPageRoute(builder: (_) => const MallScreen()));
              if (context.mounted) {
                setState(() {
                  _canRetry = true;
                  _showShopButton = false;
                  _overlayMessage = "¡Vidas recargadas!";
                });
              }
            } : null,
            onExit: () {
               if (_isVictory) widget.onSuccess();
               Navigator.pop(context);
            },
          ),
      ],
    );
  }

  Widget _buildStatPill(IconData icon, String text, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, color: color, size: 12),
          const SizedBox(width: 4),
          Text(text, style: TextStyle(color: text.startsWith('x') || text.contains('/') ? Colors.white : color, fontSize: 10, fontWeight: FontWeight.bold, decoration: TextDecoration.none)),
        ],
      ),
    );
  }

  Widget _buildVertButton(String label, Color color, VoidCallback onTap) {
    return Column(
      children: [
        GestureDetector(
          onTap: onTap,
          child: Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: color.withOpacity(0.05),
              shape: BoxShape.circle,
              border: Border.all(color: color, width: 2),
            ),
            child: Icon(Icons.add_circle, color: color, size: 18),
          ),
        ),
        const SizedBox(height: 2),
        Text(label, style: TextStyle(color: color.withOpacity(0.8), fontSize: 7, fontWeight: FontWeight.w900, decoration: TextDecoration.none)),
      ],
    );
  }

  Widget _buildColorCircle(String label, Color color) {
    return Column(
      children: [
        Text(label, style: const TextStyle(color: Colors.white54, fontSize: 7, fontWeight: FontWeight.bold, decoration: TextDecoration.none)),
        const SizedBox(height: 4),
        Container(
          width: 35,
          height: 35,
          decoration: BoxDecoration(
            color: color,
            shape: BoxShape.circle,
            border: Border.all(color: Colors.white24, width: 2),
          ),
        ),
      ],
    );
  }
}
